version: 2
jobs:
  build:
    working_directory: ~/app
    parallelism: 4
    shell: /bin/bash --login

    docker:
    - image: circleci/ruby:2.5.5-node

    steps:
    - checkout
    - setup_remote_docker

    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
    - run: bundle install
    - run: gem install hound-cli
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - vendor/bundle
    - run:
        command: bundle exec rspec --color --require spec_helper --format=doc --format progress $(circleci tests glob spec/**/*_spec.rb | circleci tests split)
        environment:
          RAILS_ENV: test
          RACK_ENV: test
