version: 2
jobs:
  build:
    working_directory: ~/app
    parallelism: 4

    docker:
    - image: circleci/ruby:2.5.1-stretch
      environment:
        RAILS_ENV: test
        RACK_ENV: test

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
    - run: bundle install
    - run: gem install hound-cli
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - vendor/bundle
    - run:
        command: bundle exec rspec --color --require spec_helper --format=doc --format progress $(circleci tests glob spec/**/*_spec.rb | circleci tests split)
