version: 2
jobs:
  build:
    working_directory: ~/app
    parallelism: 4
    shell: /bin/bash --login

    docker:
    - image: circleci/ruby:2.5.5-node
      environment:
        GEM_HOME: /home/circleci/app/vendor/bundle
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
        BUNDLE_PATH: /home/circleci/app/vendor/bundle

    steps:
    - checkout
    - setup_remote_docker

    - restore_cache:
        keys:
          - potassium-bundle-{{ .Branch }}-
          - potassium-bundle-master-
          - potassium-bundle-
    - run: gem install bundler:2.0.2
    - run: bundle install
    - run: gem install hound-cli
    - run:
        command: bundle exec rspec --color --require spec_helper --format=doc --format progress $(circleci tests glob spec/**/*_spec.rb | circleci tests split)
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    - save_cache:
        key: potassium-bundle-{{ .Branch }}-{{ epoch }}
        paths:
          - vendor/bundle
