version: 2
jobs:
  build:
    working_directory: ~/app
    parallelism: 4
    shell: /bin/bash --login

    docker:
    - image: circleci/ruby:2.7.0-node
      environment:
        GEM_HOME: /home/circleci/app/vendor/bundle
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
        BUNDLE_PATH: /home/circleci/app/vendor/bundle

    steps:
    - checkout
    - setup_remote_docker

    - restore_cache:
        keys:
          - potassium-bundle-{{ .Branch }}-
          - potassium-bundle-master-
          - potassium-bundle-
    - run: gem install bundler:2.0.2
    - run: bundle _2.0.2_ install
    - run: gem install hound-cli
    - run:
        command: |
          bundle exec rspec --color --require spec_helper --profile 10 \
                            --format progress --format documentation \
                            --format RspecJunitFormatter --out test_results/rspec.xml \
                            $(circleci tests glob spec/**/*_spec.rb | circleci tests split --split-by=timings)
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    - save_cache:
        key: potassium-bundle-{{ .Branch }}-{{ epoch }}
        paths:
          - vendor/bundle
    - store_test_results:
        path: test_results
